name: Build AgonDev

on:
  push:
  workflow_dispatch:

jobs:
  build-agondev:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Download LLVM artifact from another workflow run
        shell: pwsh
        run: |
          $Artifact = Invoke-RestMethod `
            -Headers @{ Authorization = "Bearer $env:GITHUB_TOKEN" } `
            -Uri "https://api.github.com/repos/${{ github.repository }}/actions/artifacts"

          $Found = $Artifact.artifacts | Where-Object { $_.name -eq "llvm-ez80-msvc" }

          Invoke-WebRequest `
            -Headers @{ Authorization = "Bearer $env:GITHUB_TOKEN" } `
            -Uri $Found.archive_download_url `
            -OutFile "llvm.zip"

          Expand-Archive llvm.zip -DestinationPath llvm-build

      - name: Setup MSYS2 (MINGW64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false
          install: |
            mingw-w64-x86_64-python
            mingw-w64-x86_64-python-pip
            git
            zip
            make
            cmake
            texinfo
            ninja
            gmp-devel
            mpfr-devel
            bison
            flex
            mingw-w64-x86_64-python-ply
            zlib-devel
            diffutils
            mingw-w64-x86_64-gcc
            binutils

      - name: Add MINGW64 Python to PATH
        run: |
          echo "${{ steps.setup-msys2.outputs.msys2-location }}/mingw64/bin" >> "$GITHUB_PATH"

      - name: Verify Python
        run: |
          python --version
          pip --version

      - name: Run make_llvmtools.sh
        run: |
          ./make_llvmtools.sh

      - name: Build final AgonDev package
        run: |
          make clean || true
          make -j$(nproc)

      - name: Upload final release artifact
        uses: actions/upload-artifact@v5
        with:
          name: agondev-${{ github.ref_name }}
          path: release/
